DEBUG_PRINT = True

# ERROR CODE
ERROR_CODE_BASE = 0

# MESSGAE TYPE
MESSAGE_TYPE_BASE = 0
MESSAGE_TYPE_ADB_ERROR_QUIT = 1

WORKING_TYPE_PULL_AND_MERGE = 0
WORKING_TYPE_MERGE = 1
WORKING_TYPE_PULL_AND_SAVE = 2


UI_VERSION = "1.0.0.0"
MODULE_VERSION = "1.0.0.0"
DB_VERSION = 1