from PyQt5.QtGui import QColor

DEBUG_PRINT = True

# ERROR CODE
ERROR_CODE_BASE = 0
ERROR_CODE_SUCCESS = ERROR_CODE_BASE
ERROR_CODE_INVALID_PARAM = 1

ERROR_CODE_DB_INSERT_FAILED = 10

# MESSAGE TYPE
MESSAGE_TYPE_INFO = 0
MESSAGE_TYPE_WARNING = 1

MESSAGE_STR_SUCCESS = "运行成功！"
MESSAGE_STR_ADB_ERROR_QUIT = "未找到有效的adb路径。请先将adb配置到PATH环境变量中。"
MESSAGE_STR_PARSER_EMPTY_INPUT = "请输入有效的log等级定义。"
MESSAGE_STR_INVALID_PARAM = "无效的输入。请检查后重新输入。"
MESSAGE_STR_DB_INSERT_FAILED = "写入数据库失败。"
MESSAGE_STR_SEARCH_FAILED = "没有找到匹配的项目。"
MESSAGE_STR_NO_MASK = "没有找到对应的Mask值。请重新解析后再尝试。\n设置->解析log等级设置"

WORKING_TYPE_PULL_AND_MERGE = 0
WORKING_TYPE_MERGE = 1
WORKING_TYPE_PULL_AND_SAVE = 2


UI_VERSION = "1.0.0.0"
MODULE_VERSION = "1.0.0.0"
DB_VERSION = 1


DEVICE_INFO_ID = "deviceId"
DEVICE_INFO_NAME = "deviceName"
DEVICE_INFO_STATUS = "deviceStatus"

TOOLS_ROOT_DIR = "adbTools"
TOOLS_DB_MANE = "adbTools.db"

LIST_SELECTED_COLOR = QColor(0, 0, 255, 100)
LIST_NORMAL_COLOR = QColor(255, 255, 255, 255)