# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'About.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aboutWiget(object):
    def setupUi(self, aboutWiget):
        aboutWiget.setObjectName("aboutWiget")
        aboutWiget.resize(490, 212)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(aboutWiget.sizePolicy().hasHeightForWidth())
        aboutWiget.setSizePolicy(sizePolicy)
        aboutWiget.setAutoFillBackground(True)
        self.gridLayout = QtWidgets.QGridLayout(aboutWiget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_ico_logger = QtWidgets.QLabel(aboutWiget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ico_logger.sizePolicy().hasHeightForWidth())
        self.label_ico_logger.setSizePolicy(sizePolicy)
        self.label_ico_logger.setBaseSize(QtCore.QSize(0, 0))
        self.label_ico_logger.setPixmap(QtGui.QPixmap(":/lable_icon/resource/app_icon.svg"))
        self.label_ico_logger.setScaledContents(True)
        self.label_ico_logger.setObjectName("label_ico_logger")
        self.horizontalLayout_2.addWidget(self.label_ico_logger)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lable_name = QtWidgets.QLabel(aboutWiget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lable_name.setFont(font)
        self.lable_name.setTextFormat(QtCore.Qt.AutoText)
        self.lable_name.setScaledContents(False)
        self.lable_name.setObjectName("lable_name")
        self.verticalLayout.addWidget(self.lable_name)
        self.label_home_link = QtWidgets.QLabel(aboutWiget)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_home_link.setFont(font)
        self.label_home_link.setOpenExternalLinks(True)
        self.label_home_link.setObjectName("label_home_link")
        self.verticalLayout.addWidget(self.label_home_link)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_description = QtWidgets.QLabel(aboutWiget)
        self.label_description.setFrameShape(QtWidgets.QFrame.Box)
        self.label_description.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_description.setLineWidth(1)
        self.label_description.setMidLineWidth(0)
        self.label_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_description.setWordWrap(True)
        self.label_description.setOpenExternalLinks(False)
        self.label_description.setObjectName("label_description")
        self.verticalLayout_2.addWidget(self.label_description)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ok = QtWidgets.QPushButton(aboutWiget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ok.sizePolicy().hasHeightForWidth())
        self.pushButton_ok.setSizePolicy(sizePolicy)
        self.pushButton_ok.setAutoDefault(True)
        self.pushButton_ok.setDefault(True)
        self.pushButton_ok.setFlat(False)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(aboutWiget)
        self.pushButton_ok.clicked.connect(aboutWiget.close)
        QtCore.QMetaObject.connectSlotsByName(aboutWiget)

    def retranslateUi(self, aboutWiget):
        _translate = QtCore.QCoreApplication.translate
        aboutWiget.setWindowTitle(_translate("aboutWiget", "关于"))
        self.lable_name.setAccessibleName(_translate("aboutWiget", "ADBLogger"))
        self.lable_name.setText(_translate("aboutWiget", "AndroidLogs"))
        self.label_home_link.setText(_translate("aboutWiget", "<A href=\'https://github.com/doyee/ADBLogger\'> https://github.com/doyee/AndroidLogs </a>"))
        self.label_description.setText(_translate("aboutWiget", "  AndroidLogs 是一款超轻量级日志手机整理工具,方便开发者在 MTK,Qualcomm 平台收集流水日志(/data/log/android_logs)。\n"
" \n"
" 把零散的.gz文件日志解压后合并成单一的.txt文件方便阅读，设置日志等级直接应用到手机等。"))
        self.pushButton_ok.setText(_translate("aboutWiget", "确定"))
import app_icons_rc
