# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DownloadDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DownloadDialog(object):
    def setupUi(self, DownloadDialog):
        DownloadDialog.setObjectName("DownloadDialog")
        DownloadDialog.setWindowModality(QtCore.Qt.NonModal)
        DownloadDialog.resize(400, 120)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DownloadDialog.sizePolicy().hasHeightForWidth())
        DownloadDialog.setSizePolicy(sizePolicy)
        DownloadDialog.setMinimumSize(QtCore.QSize(400, 120))
        DownloadDialog.setMaximumSize(QtCore.QSize(400, 120))
        self.gridLayout = QtWidgets.QGridLayout(DownloadDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DownloadDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(DownloadDialog)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_download_speed = QtWidgets.QLabel(DownloadDialog)
        self.label_download_speed.setObjectName("label_download_speed")
        self.horizontalLayout.addWidget(self.label_download_speed)
        self.label_time_left = QtWidgets.QLabel(DownloadDialog)
        self.label_time_left.setObjectName("label_time_left")
        self.horizontalLayout.addWidget(self.label_time_left)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(DownloadDialog)
        QtCore.QMetaObject.connectSlotsByName(DownloadDialog)

    def retranslateUi(self, DownloadDialog):
        _translate = QtCore.QCoreApplication.translate
        DownloadDialog.setWindowTitle(_translate("DownloadDialog", "更新"))
        self.label.setText(_translate("DownloadDialog", "正在下载,请稍后..."))
        self.label_download_speed.setAccessibleName(_translate("DownloadDialog", "当前下载速度："))
        self.label_download_speed.setText(_translate("DownloadDialog", "当前下载速度："))
        self.label_time_left.setAccessibleName(_translate("DownloadDialog", "预计剩余时间："))
        self.label_time_left.setText(_translate("DownloadDialog", "预计剩余时间："))
