# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogLevelParserPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogLevelParserPanel(object):
    def setupUi(self, LogLevelParserPanel):
        LogLevelParserPanel.setObjectName("LogLevelParserPanel")
        LogLevelParserPanel.resize(498, 242)
        LogLevelParserPanel.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(LogLevelParserPanel)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(LogLevelParserPanel)
        self.plainTextEdit.setPlaceholderText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_reset = QtWidgets.QPushButton(LogLevelParserPanel)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout.addWidget(self.pushButton_reset)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_cancel = QtWidgets.QPushButton(LogLevelParserPanel)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.pushButton_apply = QtWidgets.QPushButton(LogLevelParserPanel)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.horizontalLayout.addWidget(self.pushButton_apply)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(LogLevelParserPanel)
        QtCore.QMetaObject.connectSlotsByName(LogLevelParserPanel)

    def retranslateUi(self, LogLevelParserPanel):
        _translate = QtCore.QCoreApplication.translate
        LogLevelParserPanel.setWindowTitle(_translate("LogLevelParserPanel", "日志分组解析"))
        self.pushButton_reset.setText(_translate("LogLevelParserPanel", "重置"))
        self.pushButton_cancel.setText(_translate("LogLevelParserPanel", "取消"))
        self.pushButton_apply.setText(_translate("LogLevelParserPanel", "解析"))
